#include <iostream>
#include <fstream>
#include <filesystem>
#include <thread>
#include <string>
#include <chrono>

namespace fs = std::filesystem;

// The function that prints out specific dummy steps for each incoming action
void executeDummyAction(const std::string& actionStr) {
    std::cout << "\n=====================================================";
    std::cout << "\n[Client Recovery Agent] ===> EXECUTION TRIGGERED <===\n";
    
    if (actionStr == "RESTART") {
        std::cout << "[DUMMY ACTION] Clearing buffers, killing active child threads, and initializing clean boot sequence...\n";
        std::cout << "[STATUS] RESTART completed successfully.\n";
    } 
    else if (actionStr == "STOP") {
        std::cout << "[DUMMY ACTION] Flushing system log blocks, closing active file handles, and entering standby mode...\n";
        std::cout << "[STATUS] STOP completed successfully.\n";
    } 
    else if (actionStr == "DISABLE") {
        std::cout << "[DUMMY ACTION] Revoking network system authentication tokens, updating circuit breakers, and disabling application entry points...\n";
        std::cout << "[STATUS] SERVICE PERMANENTLY DISABLED.\n";
    } 
    else if (actionStr == "START") {
        std::cout << "[DUMMY ACTION] Revoking network system authentication tokens, updating circuit breakers, and disabling application entry points...\n";
        std::cout << "[STATUS] SERVICE PERMANENTLY STARTED.\n";
    } 
    else {
        std::cout << "[WARNING] Received an unrecognised recovery action command: " << actionStr << "\n";
    }
    std::cout << "=====================================================\n";
}

// Background directory watcher: checks the .state file generated by the scheduler
void checkForRecoveryCommands(const fs::path& mailboxDir, const std::string& serviceName, fs::file_time_type& lastSeenTime) {
    fs::path stateFile = mailboxDir / (serviceName + ".state");
    
    std::error_code ec;
    if (!fs::exists(stateFile, ec)) return;

    auto currentModTime = fs::last_write_time(stateFile, ec);
    if (ec || currentModTime <= lastSeenTime) return;

    // Update time anchor so we don't parse the same file state twice
    lastSeenTime = currentModTime;

    // Short gap window ensuring the scheduler's atomic rename block has fully flushed to disk
    std::this_thread::sleep_for(std::chrono::milliseconds(50));

    std::ifstream in(stateFile);
    std::string line;
    std::string foundAction = "";

    while (std::getline(in, line)) {
        if (line.rfind("Last_Action_Executed: ", 0) == 0) {
            foundAction = line.substr(22); // Extract action string block
            break;
        }
    }

    if (!foundAction.empty()) {
        executeDummyAction(foundAction);
    }
}

// Thread function dedicated strictly to seeking user input to trigger failures
void inputListenerThread(const fs::path& mailboxDir, const std::string& serviceName) {
    std::string command;
    // Let initial screen logs settle
    std::this_thread::sleep_for(std::chrono::milliseconds(500));

    while (true) {
        std::cout << "\n[Interactive Simulation] Type 'fail' to create a crash / failure (or 'exit'): " << std::flush;
        std::cin >> command;

        if (command == "exit") {
            std::cout << "[Interactive Simulation] Stopping user input thread.\n";
            break;
        }
        else if (command == "fail") {
            std::cout << "[Simulation] Dropping failure alert token: " << serviceName << ".fail\n" << std::flush;
            
            // Instantly drops the text token to trigger the scheduler server
            std::ofstream file(mailboxDir / (serviceName + ".fail"));
            file.close();
        }
        else {
            std::cout << "[Simulation Error] Invalid command. Please type 'fail' or 'exit'.\n" << std::flush;
        }
    }
}

int main() {
    fs::path mailboxDir = fs::current_path() / "ipc_mailbox";
    std::string identityName = "auth-service";

    // Setup file modification time tracking anchor
    std::error_code ec;
    fs::file_time_type lastSeenTime = fs::exists(mailboxDir / (identityName + ".state"), ec) 
                                      ? fs::last_write_time(mailboxDir / (identityName + ".state"), ec)
                                      : fs::file_time_type::min();

    std::cout << "=====================================================\n";
    std::cout << "        MONITORED SERVICE APPLICATION TERMINAL        \n";
    std::cout << "=====================================================\n";
    std::cout << " Identity Name: " << identityName << "\n";
    std::cout << " Mailbox Path:  " << mailboxDir.string() << "\n";
    std::cout << "=====================================================\n";

    // 🚀 Start the dedicated background thread for user input
    std::thread inputThread(inputListenerThread, mailboxDir, identityName);

    std::cout << "[Service Client Process] Background listener loop is active. Awaiting actions...\n";

    // Continuous file monitoring loop running on the main thread
    while (true) {
        checkForRecoveryCommands(mailboxDir, identityName, lastSeenTime);
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
        
        // Break out gracefully if the user types 'exit' inside the input thread
        // We use an asynchronous check to see if the thread finished execution
        static bool threadLoggedDead = false;
        if (!threadLoggedDead && !inputThread.joinable()) {
            break;
        }
    }

    // Join the thread cleanly if it hasn't exited already
    if (inputThread.joinable()) {
        inputThread.join();
    }
    return 0;
}
